### ISSUE TITLE
Post-processing job gets stuck when using MPI 

### ISSUE THREAD

**Issue by gewitterblitz** [matzegoebel/WRFlux#3] opened 2024-07-24 20:18 UTC
Hi @matzegoebel,

I am trying to calculate the tendencies in the post-processing step using the fluxes from the online calculations. Although slow when using a single core (due to the size of model output), it works well.  However, when I try using multiple cores on a single node (max of 48 cores on 1 node), I start running into issues. I used a wall-time of 1 hour which is enough for this job, but the script did not even get past the first variable `Q` (mixing ratio), even when the order of variables in the `tendencies_calc.py` script was set to `variables = ["t", "q", "u", "v", "w"] ` .  

I was hoping to see a new directory `postprocessed` containing a separate subdirectory for each of the variables listed above, with the following files:

```
1. corr_avg_y.nc
2. flux_avg_y.nc
3. grid_avg_y.nc
5. tend_avg_y.nc
6. tend_mass_avg_y.nc
``` 
However, I only see the `Q` subdirectory after 1 hour of job time and the tendencies files (bottom two in the list above) were not generated at all.

A sample log file from one of the 12 tasks looks like this:

```
./output/meanout_d01_2022-08-09_21:00:00 ./output/wrfout_d01_2022-08-09_21:00:00
Create tasks
Load model output
##############################
Process tile: {'x': slice(69, 81, None), 'x_stag': slice(69, 82, None)}
Prepare data
####################
Process variable Q
Prepare tendency calculations for Q
Compute SGS and additional tendencies
Budget form: native
Compute resolved tendencies
Budget form: cartesian
Compute resolved tendencies
Compute Cartesian corrections
Budget form: cartesian adv_form
Compute resolved tendencies
Compute Cartesian corrections
Save data
```

This is the SLURM job submission script I used:

```

#!/bin/bash
#SBATCH --export=ALL 
#SBATCH --job-name=wrflux_post_cont
#SBATCH --time=01:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=48 
#SBATCH --cpus-per-task=1 
#SBATCH --mem=360G
#SBATCH --error=/scratch/user/milindsharma/manuscript_runs/continental_run/stdout/wrflux.error.%j
#SBATCH --output=/scratch/user/milindsharma/manuscript_runs/continental_run/stdout/wrflux.%j
# activate the conda environment
source /sw/eb/sw/Anaconda3/2022.10/etc/profile.d/conda.sh
conda activate wrflux
#END_OF_INSERTION
ulimit -s unlimited
mpiexec -n 12 ./tendency_calcs.py
```

**Comment by matzegoebel** [comment] 2024-07-31 11:34
Hi @gewitterblitz ,
thanks for reporting this issue. I haven't tested the parallel processing for a while and maybe some other changes led to this feature not working anymore. I identified and fixed the problem and also some other issues with the parallel processing. So it works on my computer now. Could you pull the latest commits and tell me if it works for you now? Thanks.

There is still a problem with u tendencies (if chunking is in x-direction) and v tendencies (if chunking is in y-direction) in the advective form. The tendencies are then not correct at the tile boundaries. Let me know, if this affects you. Then I could try to fix that too.

**Comment by matzegoebel** [comment] 2024-07-31 11:37
Also, I haven't used the tiled and parallel processing much, because my simulations were always small enough to fit into memory. So I'm not sure how useful that feature actually is. Let me know what you think, when you tried it.

**Comment by matzegoebel** [comment] 2024-08-16 08:43
@gewitterblitz Have you tried out the latest version?

**Comment by milindsharma1** [comment] 2024-08-16 15:53
@matzegoebel Thank you for your swift action on this issue. Appreciate your help!

Sorry for the delayed response. The original issue of the MPI processes abruptly getting stuck is definitely resolved. I was able to generate the postprocessed output for all variables (Q,T,U,V,and W). I used 48 cores with a wall-time of 45 minutes for the SLURM job. However, with only 120 grid points in both the x and y directions and a default chunking of 10 in the x-direction, some cores didn’t receive any tiles to process, which is understandable.

One thing I noticed was that even though the post-processing step finished about 30 minutes into the SLURM job (as confirmed by checking the .log file with tail -f), the job didn’t automatically terminate. However, I don’t think this is a significant issue.

I did not notice any immediate discrepancies with the u-tendencies, but that could be because I haven't looked at the output thoroughly yet.

**Comment by matzegoebel** [comment] 2024-09-08 14:45
Thanks for checking and sorry for the late response. The discrepancies with the u and v-tendencies only appear for the advective form of the tendencies (`adv_form` in `budget_forms`). So maybe that's why you didn't notice it. I will close this issue now. Feel free to reopen it if there is still a problem with the MPI processing or open another one if a new problem comes up.

**Closed as completed by matzegoebel** 2024-09-08 14:45 UTC
